CREATE DATABASE RECEITAWS;
USE RECEITAWS;

CREATE TABLE USUARIO(
	USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USUARIO_NOME VARCHAR(100),
  USUARIO_EMAIL VARCHAR(50),
  USUARIO_SENHA VARCHAR(20)
);

CREATE TABLE EMPRESA(
EMPRESA_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  EMPRESA_NOME_EMPRESARIAL VARCHAR(40),
  EMPRESA_NOME_FANTASIA VARCHAR(40),
  EMPRESA_CNPJ VARCHAR(18),
  EMPRESA_SITUACAO VARCHAR(40),
  EMPRESA_ABERTURA VARCHAR(8),
  EMPRESA_TIPO VARCHAR(20),
  EMPRESA_NATUREZA_JURIDICA VARCHAR(255),
  EMPRESA_ATIVIDADE_PRINCIPAL VARCHAR(100),
  EMPRESA_LOGRADOURO VARCHAR(100),
  EMPRESA_NUMERO INT,
  EMPRESA_COMPLEMENTO VARCHAR(250),
  EMPRESA_BAIRRO VARCHAR(40),
  EMPRESA_MUNICIPIO VARCHAR(40),
  EMPRESA_UF VARCHAR(2),
  EMPRESA_CEP VARCHAR(8),
  USUARIO_ID INT NOT NULL,
  FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);
